"""Leetcode 389. Find the Difference
Easy

URL: https://leetcode.com/problems/find-the-difference/

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then 
add one more letter at a random position.

Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"
Output:
e
Explanation:
'e' is the letter that was added.
"""

class SolutionSortPointer(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        pass


def main():
    # Output: e
    s = "abcd"
    t = "abcde"
    print SolutionSortPointer().findTheDifference(s, t)


if __name__ == '__main__':
    main()
